openapi: 3.0.3
info:
  title: Utbetalingsdetaljer mot utbetaling/helved
  version: 1.0.0
paths: {}
components:
  schemas:
    Utbetaling:
      type: object
      required:
        - behandlingId
        - meldekortId
        - ident
        - utbetalinger
      properties:
        behandlingId:
          type: string
          format: uuid
        meldekortId:
          type: string
        ident:
          type: string
        utbetalinger:
          type: array
          items:
            $ref: '#/components/schemas/Utbetalingsdag'
    Utbetalingsdag:
      type: object
      required:
        - meldeperiode
        - dato
        - sats
        - utbetaltBeløp
      properties:
        meldeperiode:
          type: string
        dato:
          type: string
          format: date
        sats:
          type: integer
          format: int32
        utbetaltBeløp:
          type: integer
          format: int32