openapi: 3.0.0
info:
  title: Utbetaling API
  version: 1.0.2
  description: API for å hente alle utbetalinger.
  contact:
    name: '#team-dagpenger'
servers:
  - url: https://dp-mellom-barken-og-veden.intern.dev.nav.no
    description: dev
  - url: https://dp-mellom-barken-og-veden.intern.nav.no
    description: prod
paths:
  /utbetaling/{behandlingId}:
    get:
      summary: Hent utbetaling for behandling
      operationId: hentUtbetaling
      parameters:
        - name: behandlingId
          in: path
          required: true
          description: Behandlingens id
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utbetaling'
        404:
          description: behandling ikke funnet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpProblem'

        500:
          description: Noe gikk galt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpProblem'

components:
  schemas:
    Utbetaling:
      type: object
      required:
        - behandlingId
        - status
        - opprettet
      properties:
        behandlingId:
          type: string
          format: uuid
          description: Behandlingens id
        tilstand:
          type: string
          description: Tilstand på utbetalingen
        opprettet:
          type: string
          format: date-time
          description: Dato og tidspunkt for opprettelse av utbetalingen
        utbetalingsdager:
          type: array
          items:
            $ref: '#/components/schemas/Utbetalingsdag'

    Utbetalingsdag:
      type: object
      required:
        - dato
        - sats
        - utbetaltBeløp
      properties:
        dato:
          type: string
          format: date
          description: Dato for utbetalingen
        sats:
          type: number
          format: double
          description: Vedtaksatsen for utbetalingen
        utbetaltBeløp:
          type: number
          format: double
          description: Totalt beløp som er utbetalt for denne dagen

    HttpProblem:
      type: object
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          description: A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type
        title:
          type: string
          description: A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization
        status:
          type: integer
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          format: uri
          description: A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced


  securitySchemes:
    azureAd:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Bruker [AzureAD](https://docs.nais.io/security/auth/azure-ad) til autentisering. 
        Token må ha `audience` satt til `[cluster].teamdagpenger.dp-mellom-barken-og-veden`.
        
        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwalled:
        - [dev-gcp](https://azure-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp.teamdagpenger.dp-mellom-barken-og-veden)
